targets:
  $default:
    sources:
      - lib/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "input_folder/"
          output_folder: "lib/swagger_generated_code/"
          input_urls:
            - url: "https://d2f342b322090cbb.platform.connectedtech.dev/swagger/doc.json"
          with_base_url: true
          with_converter: true
          use_path_for_request_names: true
          use_default_null_for_lists: false
          override_equals_and_hashcode: true
          build_only_models: false
          additional_headers:
            - "Cache-Control"
